ALTER TABLE "Belief" ADD COLUMN     "muBar" DOUBLE PRECISION,
ADD COLUMN     "muGap" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "varBar" DOUBLE PRECISION,
ADD COLUMN     "varGap" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[];

ALTER TABLE "MatchDecision" ADD COLUMN     "learnedAt" TIMESTAMP(3);
